- name: Install and Configure Apache Web Server on all App Servers
  hosts: all
  become: yes
  become_user: root
  
  tasks:
  - name: Install apache web server
    yum:
        name: httpd
        state: present

  - name: Start apache web service
    service:
        name: httpd
        state: started

  - name: Create the index.html file
    copy:
        dest: /var/www/html/index.html
        content: |
            This is a Nautilus sample file, created using Ansible!

  - name: Insert line at the beginning of the file
    lineinfile:
        path: /var/www/html/index.html
        line: "Welcome to xFusionCorp Industries!"
        insertbefore: BOF

  - name: Set the file permissions and owner to 'apache'
    file:
        path: /var/www/html/index.html
        owner: apache
        group: apache
        mode: "0777"