- name: Ansible file
  hosts: all
  become: yes
  tasks:
   - name: Extract directory to remote
     ansible.builtin.unarchive:
       src: /usr/src/itadmin/xfusion.zip
       dest: /opt/itadmin/
       mode: '0777'
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"