apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
     app: drupal
  ports:
    - port: 80
      nodePort: 30095

---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  type: ClusterIP
  selector:
     app: drupal-mysql
  ports:
     - name: mysql
       protocol: TCP
       port: 3306
       targetPort: 3306