version: '3'
services:
    web:
        build: .
        container_name:  python
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis_app

    redis_app:
        image: redis
        container_name: redis

