version: '1'
services:
    web:
        image: .
        container_name:  python
        ports:
            - "5000:5000"
        volume:
            - .:/code
        depend:
            - redis_app

    redis_app:
        build: redis
        container_name: redis

