---
apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-namespace-datacenter
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-datacenter
  namespace: tomcat-namespace-datacenter
spec:
  type: NodePort
  selector:
    app: tomcat-container-datacenter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32227
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-datacenter
  namespace: tomcat-namespace-datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-container-datacenter
  template:
    metadata:
      labels:
        app: tomcat-container-datacenter
    spec:
      containers:
      - name: tomcat-container-datacenter
        image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
        ports:
        - containerPort: 8080