---
apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
  labels:
    app: httpd
    name: pod-datacenter
spec:
  containers:
    - name: secret-container-devops
      image: debian:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: secret-storage
          mountPath: /opt/games
          readOnly: true
  volumes:
    - name: secret-storage
      secret:
        secretName: news