---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app-container
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30012
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-container
  template:
    metadata:
      labels:
        app: node-app-container
    spec:
      containers:
      - name: node-app-container
        image: gcr.io/kodekloud/centos-ssh-enabled:node
        ports:
        - containerPort: 8080