- name: Ansbile Add User & Group                                                                       
  hosts: stapp02
  become: yes
  tasks:
  - name: Creating Admin Groups                                                                                  
    group:                                                                                                       
     name:                                                                                                       
      admins                                                                                                     
     state: present                                                                                              
  - name: Creating Dev Groups                                                                                    
    group:                                                                                                       
     name:                                                                                                       
      developers                                                                                                 
     state: present                                                                                              
  - name: Creating Admins Group Users                                                                            
    user:                                                                                                        
     name: "{{ item }}"                                                                                          
     password: "{{ 'B4zNgHA7Ya' | password_hash ('sha512') }}"                                                   
     groups: admins,wheel
     state: present                                                                                              
    loop:                                                                                                        
    - rob                                                                                                        
    - david                                                                                                        
    - joy                                                                                                      
  - name: Creating Developers Group Users                                                                        
    user:                                                                                                        
     name: "{{ item }}"                                                                                          
     password: "{{ 'dCV3szSGNA' | password_hash ('sha512') }}"                                                   
     home: "/var/www/{{ item }}"                                                                                             
     group: developers                                                                                           
     state: present                                                                                              
    loop:                                                                                                        
    - tim                                                                                                        
    - ray                                                                                                        
    - jim                                                                                                       
    - mark 