apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
  labels:
    name: myapp
spec:
  volumes:
    - name: volume-share
      emptyDir: {}
  containers:
  - name: volume-container-datacenter-1
    image: centos:latest
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
      - mountPath: /tmp/official
        name: volume-share
  - name: volume-container-datacenter-2
    image: centos:latest
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
      - mountPath: /tmp/cluster
        name: volume-share
