---
- hosts: stapp01
  become: yes
  become_user: root
  
  tasks:
    - name: Install httpd
      package:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes

    - name: Replace default DocumentRoot
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'DocumentRoot "/var/www/html"'
        replace: 'DocumentRoot "/var/www/html/myroot"'

    - name: Create new DocumentRoot directory
      file:
        path: /var/www/html/myroot
        state: directory
        mode: '0755'
        owner: apache
        group: apache

    - name: use Jinja2 to generate phpinfo.php
      template:
        src: phpinfo.php.j2
        dest: /var/www/html/myroot/phpinfo.php
        mode: '0644'
        owner: apache
        group: apache

    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes
