apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-gallery-deployment-xfusion
  namespace: iron-namespace-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iron-gallery
  template:
    metadata:
      labels:
        run: iron-gallery
    spec:
      containers:
      - name: iron-gallery-container-xfusion
        image: kodekloud/irongallery:2.0
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "50m"
        volumeMounts:
          - mountPath: /usr/share/nginx/html/data
            name: config
          - mountPath: /usr/share/nginx/html/uploads
            name: images
        ports:
        - containerPort: 8080
    volumes:
    - name: config
      emptyDir: {}
    - name: images
      emptyDir: {}
          
  
